function hockeynet_perp


angle = 90;          % 90 = perp to walker,   180 parallel

l = -20;             % +ive in front of person, -ive behind person
w = -300;            % -ive to the right  ; +ive to the left
h = 0;               % height off the ground + ive up

position = [l, w, h];

xd = (-2.5:.5:2.5);
yd = sqrt(2.5^2-xd.*xd);
xd = [xd,fliplr(xd)];
yd = [yd,-yd];
zd = zeros(size(yd));
r = 4*35/(2*pi);

vplate = [xd',yd',zd'];
nvplate = displace(vplate,[0 r-2.5 0]);
bvplate = vecrotate(vecrotate(displace(vplate,[0 100 0]),90,'y'),30,'z');

%bvplate = vecrotate(vecrotate(displace(vplate,[0 100 0]),0,'y'),30,'z');

tvplate = vecrotate(displace(vplate,[0 15 0]),90,'y');
plength = length(xd);
h = 127.7183-3.5-19.5;
fplate = [(1:plength-1)',(2:plength)',(plength+2:2*plength)',(plength+1:2*plength-1)'];

vr = [nvplate;displace(nvplate,[0 0 h]);...
    displace(vecrotate(nvplate,10,'x'),[0 0 h]);...
    displace(vecrotate(nvplate,20,'x'),[0 0 h]);...
    displace(vecrotate(nvplate,30,'x'),[0 0 h]);...
    displace(vecrotate(nvplate,40,'x'),[0 0 h]);...
    displace(vecrotate(nvplate,50,'x'),[0 0 h]);...
    displace(vecrotate(nvplate,60,'x'),[0 0 h]);...
    displace(vecrotate(nvplate,70,'x'),[0 0 h]);...
    displace(vecrotate(nvplate,80,'x'),[0 0 h]);...
    displace(vecrotate(nvplate,90,'x'),[0 r-97 h])];

fc = [fplate;...
    fplate+plength;...
    fplate+2*plength;...
    fplate+3*plength;...
    fplate+4*plength;...
    fplate+5*plength;...
    fplate+6*plength;...
    fplate+7*plength;...
    fplate+8*plength;...
    fplate+9*plength;];

% adding the base
vr = displace(vr,[0 -max(vr(:,2))+97 0]);
ds = mean(vr(1:plength,:))-mean(bvplate);
ds(3) = ds(3)+2.5;

vr = flipud(vr);


vr = [vr;displace(bvplate,ds);...
    displace(vecrotate(bvplate,10,'z'),ds);...
    displace(vecrotate(bvplate,20,'z'),ds);...
    displace(vecrotate(bvplate,30,'z'),ds);...
    displace(vecrotate(bvplate,40,'z'),ds);...
    displace(vecrotate(bvplate,50,'z'),ds);...
    displace(vecrotate(bvplate,60,'z'),[ds(1),0,ds(3)])];

fc = [fc;...
    fplate+plength*10;...
    fplate+plength*11;...
    fplate+plength*12;...
    fplate+plength*13;...
    fplate+plength*14;...
    fplate+plength*15;...
    fplate+plength*16];



ds = mean(vr(1:plength,:))-mean(tvplate)+[0 75 0];

vr = [vr;displace(tvplate,ds);...
    displace(tvplate,ds+[-15 0 0]);...
    displace(vecrotate(tvplate,30,'z'),ds+[-15 0 0]);...
    displace(vecrotate(tvplate,60,'z'),ds+[-15 0 0]);...
    displace(vecrotate(tvplate,90,'z'),ds+[-15 0 0]);...
    displace(vecrotate(tvplate,90,'z'),[ds(1)-15 0 ds(3)])];

fc = [fc;...
    fplate+plength*18;...
    fplate+plength*19;...
    fplate+plength*20;...
    fplate+plength*21;...
    fplate+plength*22];



nvr = vr;
nvr(:,2) = -nvr(:,2);
fc = [fc;length(vr(:,1))+fc];
vr = [vr;nvr];


%----------DETERMINES POSITION OF NET---
vr = vecrotate(vr,angle,'z');   
vr = displace(vr,position);
%-------------



if nargout==2
    varargout{1} = vr;
    varargout{2} = fc;
else


 patch('parent',finddobj('axes'),'faces',fc,'vertices',vr,'facecolor',[1 0 0],'edgecolor','none','facelighting','gouraud','clipping','off','tag','net');




end












