function data = cocontraction_data(data,muscle_pairs)


% dcocontraction(data,muscle_pairs) computes co-contraction indices 
%
% ARGUMENTS
%  data     ...  zoo struct
%  pairs    ...   Names of muscle pairs (cell array of strings). Default = {'VM_MG','VM_MH','VL_LG','VL_LH'}
%
% RETURNS
%  data     ...  updated zoo struct

% NOTES
% - 'Full_waveforms.mat' must first be generated by 'knee_OA_gather.m'
% - 'Full_waveforms.mat' should reside in each subjects 'Matlab' subfolder
% - New file generated will be 'Full_waveforms_cocontract.mat'
% - Choice of muscle pairs based on Hubley-Kozey, Robbins et al., 2013):
%   vastus medialis  – medial gastrocnemius
%   vastus medialis  - medial hamstring, 
%   vastus lateralis – lateral gastrocnemius,
%   vastus lateralis – lateral hamstring  
%
% See also knee_OA_gather, muscle_cocontraction,knee_OA_cocontraction



% set defaults 
%
if nargin==1
    muscle_pairs = {'VM_MG','VM_MH','VL_LG','VL_LH'};
end

sides = {'R','L'};

for i = 1:length(muscle_pairs)
    muscles = strsplit(muscle_pairs{i},'_');
    
    for j = 1:length(sides) 
        muscle1 = data.([sides{j},muscles{1}]).line;
        muscle2 = data.([sides{j},muscles{2}]).line;
        
        r = cocontraction_line(muscle1,muscle2);
        data = addchannel_data(data,[sides{j},muscles{1},'_',sides{j},muscles{2}],r,'Analog');
    end
end

