function drawboneorientation

amat = {'Pelvis';...
    'LeftFemur';...
    'LeftTibia';...
    'LeftFoot';...
    'LeftToe';...
    'RightFemur';...
    'RightTibia';...
    'RightFoot';...
    'RightToe';...
    'Thorax';...
    'Head';...
    'LeftClavicle';...
    'LeftHumerus';...
    'LeftRadius';...
    'LeftHand';...
    'RightClavicle';...
    'RightHumerus';...
    'RightRadius';...
    'RightHand'};
    

frm = finddobj('frame','number');

[vr,fc,cdata] = k2graphics('orientation',gunit,[0 0 0],10);

prp = finddobj('props');
ax = finddobj('axes');
for i = 1:length(amat);
    hnd = findobj(prp,'tag',amat{i});
    ud = get(hnd,'userdata');
    nvr = ctransform(makeunit(ud.ort{frm}),gunit,vr);
    nvr = displace(nvr,ud.dis(frm,:));
    patch('parent',ax,'vertices',nvr,'faces',fc,'cdata',cdata,'tag','tempobj','facecolor','flat','edgecolor','none','facelighting','gouraud','clipping','off','facealpha',.99);
end