function r = plugingaitchannels;
r = {'LKAX';...
    'LKD1';...
    'LKD2';...
    'RKAX';...
    'RKD1';...
    'RKD2';...
    'T1';...
    'T2';...
    'T3';...
    'T4';...
    'T5';...
    '#';...
    'RFEP';...
    'RFEO';...
    'RTIO';...
    'LFEP';...
    'LFEO';...
    'LTIO';...
    'LHipAngles';...
    'LKneeAngles';...
    'LAnkleAngles';...
    'LAbsAnkleAngle';...
    'RHipAngles';...
    'RKneeAngles';...
    'RAnkleAngles';...
    'RAbsAnkleAngle';...
    'LShoulderAngles';...
    'LElbowAngles';...
    'LWristAngles';...
    'RShoulderAngles';...
    'RElbowAngles';...
    'RWristAngles';...
    'LNeckAngles';...
    'RNeckAngles';...
    'LSpineAngles';...
    'RSpineAngles';...
    'LHeadAngles';...
    'RHeadAngles';...
    'LThoraxAngles';...
    'RThoraxAngles';...
    'LPelvisAngles';...
    'RPelvisAngles';...
    'LFootProgressAngles';...
    'RFootProgressAngles';...
    'PELO';...
    'PELP';...
    'PELA';...
    'PELL';...
    'LFEA';...
    'LFEL';...
    'LTIP';...
    'LTIA';...
    'LTIL';...
    'LFOO';...
    'LFOP';...
    'LFOA';...
    'LFOL';...
    'LTOO';...
    'LTOP';...
    'LTOA';...
    'LTOL';...
    'RFEA';...
    'RFEL';...
    'RTIP';...
    'RTIA';...
    'RTIL';...
    'RFOO';...
    'RFOP';...
    'RFOA';...
    'RFOL';...
    'RTOO';...
    'RTOP';...
    'RTOA';...
    'RTOL';...
    'TRXO';...
    'TRXP';...
    'TRXA';...
    'TRXL';...
    'HEDO';...
    'HEDP';...
    'HEDA';...
    'HEDL';...
    'LCLO';...
    'LCLP';...
    'LCLA';...
    'LCLL';...
    'LHUO';...
    'LHUP';...
    'LHUA';...
    'LHUL';...
    'LRAO';...
    'LRAP';...
    'LRAA';...
    'LRAL';...
    'LHNO';...
    'LHNP';...
    'LHNA';...
    'LHNL';...
    'RCLO';...
    'RCLP';...
    'RCLA';...
    'RCLL';...
    'RHUO';...
    'RHUP';...
    'RHUA';...
    'RHUL';...
    'RRAO';...
    'RRAP';...
    'RRAA';...
    'RRAL';...
    'RHNO';...
    'RHNP';...
    'RHNA';...
    'RHNL';...
    'LGroundReactionForce';...
    'RGroundReactionForce';...
    'LNormalisedGRF';...
    'RNormalisedGRF';...
%     'LAnkleForce';...
%     'RAnkleForce';...
%     'LKneeForce';...
%     'RKneeForce';...
%     'LHipForce';...
%     'RHipForce';...
%     'LWaistForce';...
%     'RWaistForce';...
%     'LNeckForce';...
%     'RNeckForce';...
%     'LShoulderForce';...
%     'RShoulderForce';...
%     'LElbowForce';...
%     'RElbowForce';...
%     'LWristForce';...
%     'RWristForce';...
    'LGroundReactionMoment';...
    'RGroundReactionMoment';...
    'LAnkleMoment';...
    'RAnkleMoment';...
    'LKneeMoment';...
    'RKneeMoment';...
    'LHipMoment';...
    'RHipMoment';...
    'LWaistMoment';...
    'RWaistMoment';...
    'LNeckMoment';...
    'RNeckMoment';...
    'LShoulderMoment';...
    'RShoulderMoment';...
    'LElbowMoment';...
    'RElbowMoment';...
    'LWristMoment';...
    'RWristMoment';...
    'LAnklePower';...
    'RAnklePower';...
    'LKneePower';...
    'RKneePower';...
    'LHipPower';...
    'RHipPower';...
    'LWaistPower';...
    'RWaistPower';...
    'LNeckPower';...
    'RNeckPower';...
    'LShoulderPower';...
    'RShoulderPower';...
    'LElbowPower';...
    'RElbowPower';...
    'LWristPower';...
    'RWristPower';...
    'CentreOfMass';...
    'CentreOfMassFloor';...
    'LF1-1';...
    'LF2-1';...
    'LF3-1';...
    'LF4-1'};